@startuml
' Creates an aliased entity with a colorized sprite and stereotype
' Params:
'   e_type:     the entity type (e.g. component, node, agent, etc.)
'   e_color:    the color for the sprite
'   e_sprite:   the sprite for the AWS Icon representing the entity
'   e_alias:    the alias to give the entity
'   e_stereo:   the stereotype, which can define additional styling
!define ENTITY(e_type,e_color,e_sprite,e_alias,e_stereo) e_type "<color:e_color><$e_sprite></color>" as e_alias <<e_stereo>>

' Creates an aliased entity with a colorized sprite, label, and stereotype
' Params:
'   e_type:     the entity type (e.g. component, node, agent, etc.)
'   e_color:    the color for the sprite
'   e_sprite:   the sprite for the AWS Icon representing the entity
'   e_label:    the label to display under the sprite
'   e_alias:    the alias to give the entity
'   e_stereo:   the stereotype, which can define additional styling
!define ENTITY(e_type,e_color,e_sprite,e_label,e_alias,e_stereo) e_type "<color:e_color><$e_sprite></color>\r e_label" as e_alias <<e_stereo>>

hide stereotype

' BC
!define BASEURL https://raw.githubusercontent.com/sleepstate/plantuml-identity-sprites/refs/heads/main

!include BASEURL/puml/icon_teams.puml
!include BASEURL/puml/icon_help.puml
!include BASEURL/puml/icon_bot_detection.puml
!include BASEURL/puml/icon_monitoring.puml
!include BASEURL/puml/icon_users.puml
!include BASEURL/puml/icon_identifier_password.puml
!include BASEURL/puml/icon_spa.puml
!include BASEURL/puml/icon_auth0.puml
!include BASEURL/puml/icon_webauthn.puml
!include BASEURL/puml/icon_cli_script.puml
!include BASEURL/puml/icon_device_biometrics.puml
!include BASEURL/puml/icon_security.puml
!include BASEURL/puml/icon_identifier_first.puml
!include BASEURL/puml/icon_multiple_failed_logins.puml
!include BASEURL/puml/icon_consistency.puml
!include BASEURL/puml/icon_attributes.puml
!include BASEURL/puml/icon_efficiency.puml
!include BASEURL/puml/icon_authentication_b.puml
!include BASEURL/puml/icon_cloud.puml
!include BASEURL/puml/icon_auth0_authorization_server.puml
!include BASEURL/puml/icon_social_providers.puml
!include BASEURL/puml/icon_organizations.puml
!include BASEURL/puml/icon_mail_message_b.puml
!include BASEURL/puml/icon_guardian_push_notification.puml
!include BASEURL/puml/icon_api_related.puml
!include BASEURL/puml/icon_enterprise_directory.puml
!include BASEURL/puml/icon_biometrics.puml
!include BASEURL/puml/icon_user.puml
!include BASEURL/puml/icon_ip_throttling.puml
!include BASEURL/puml/icon_user_management.puml
!include BASEURL/puml/icon_fine_grained_authorization.puml
!include BASEURL/puml/icon_desktop_app.puml
!include BASEURL/puml/icon_integrations_marketplace.puml
!include BASEURL/puml/icon_credential_application.puml
!include BASEURL/puml/icon_branding.puml
!include BASEURL/puml/icon_web_app.puml
!include BASEURL/puml/icon_extensions.puml
!include BASEURL/puml/icon_credential_stuffing.puml
!include BASEURL/puml/icon_brute_force.puml
!include BASEURL/puml/icon_account_takeover.puml
!include BASEURL/puml/icon_login_customization.puml
!include BASEURL/puml/icon_pipeline_a.puml
!include BASEURL/puml/icon_generic_enterprise_directory.puml
!include BASEURL/puml/icon_settings.puml
!include BASEURL/puml/icon_user_db.puml
!include BASEURL/puml/icon_refresh_token.puml
!include BASEURL/puml/icon_advanced_options.puml
!include BASEURL/puml/icon_phone_message_a.puml
!include BASEURL/puml/icon_cookies.puml
!include BASEURL/puml/icon_breached_password.puml
!include BASEURL/puml/icon_sdks.puml
!include BASEURL/puml/icon_user_database.puml
!include BASEURL/puml/icon_applications.puml
!include BASEURL/puml/icon_phone_message_b_.puml
!include BASEURL/puml/icon_cookie.puml
!include BASEURL/puml/icon_getting_started.puml
!include BASEURL/puml/icon_multifactor.puml
!include BASEURL/puml/icon_dashboard.puml
!include BASEURL/puml/icon_auth0_logo_light.puml
!include BASEURL/puml/icon_pipeline.puml
!include BASEURL/puml/icon_credential_user.puml
!include BASEURL/puml/icon_activity.puml
!include BASEURL/puml/icon_certificate.puml
!include BASEURL/puml/icon_tenant.puml
!include BASEURL/puml/icon_empathy.puml
!include BASEURL/puml/icon_server.puml
!include BASEURL/puml/icon_backend.puml
!include BASEURL/puml/icon_actions.puml
!include BASEURL/puml/icon_mail_message_a.puml
!include BASEURL/puml/icon_mobile_app.puml
!include BASEURL/puml/icon_browser.puml
!include BASEURL/puml/icon_video.puml
!include BASEURL/puml/icon_auth0_dashboard.puml
!include BASEURL/puml/icon_anticipation.puml
!include BASEURL/puml/icon_id_token.puml
!include BASEURL/puml/icon_api.puml
!include BASEURL/puml/icon_authentication_a.puml
!include BASEURL/puml/icon_authorization_server.puml
!include BASEURL/puml/icon_database.puml
!include BASEURL/puml/icon_logs.puml
!include BASEURL/puml/test_file.puml
!include BASEURL/puml/icon_access_token.puml
!include BASEURL/puml/icon_auth0_logo_dark.puml
!include BASEURL/puml/icon_boundary_protocol.puml
!include BASEURL/puml/icon_one_time_password.puml
!include BASEURL/puml/icon_customization.puml
!include BASEURL/puml/icon_login.puml
!include BASEURL/puml/icon_pipeline_p.puml
!include BASEURL/puml/icon_sdk.puml
